### ISSUE TITLE
GAMEINA ERROR 404

### ISSUE THREAD

**Issue by nightshiftdevteam** [Syauqizaidan/GameINA#3]
I am getting 404 error everywhere. I uploaded the files via FTP, connected the databases. Unsure if I need to change koneksi.php but i updated the databases in the config file. When logging in as publisher or admin I recieved 404. Why are some of the links failing is this an HTACCESS issue or some broken links?

**Comment by nightshiftdevteam** [comment]
Scratch that. Ripped it from its terrible framework, applied it to REACT. Poor judgement in some of the code. Maybe a Russian thing. Lmk if you want the updated one.

**Comment by syauqi** [comment]
Have you tried it locally in your machine? can you screenshot it?

**Comment by syauqi** [comment]
Codeigniter is an old framework, i did this project with codeigniter because my teacher said so.. i will let you know if i made and updated in to laravel version

**Comment by nightshiftdevteam** [comment]
Meant no disrespect for sure. The poor judgement was more in relation to CodeIgniter. What class did you take?

**Comment by nightshiftdevteam** [comment]
I was just getting 404 errors everywhere. The reason I used yours for my client is that it had everything he was looking for and made the job easier.

**Comment by MeizalunaWulandari** [comment]
it's a common problem of windows users.
the solution you have to change the file name according to the standard codeigniter. 
Ex Home.php instead home.php
